[programs.localnet]
gem_bank = "Ee5s23sQ7k4RkAZ6zaTuaCdVkAAGwfsd5r1naH25LUeW"
gem_farm = "8ptT7jx1XqLfTYAES4bj5MzhvoXji4vaBNce6KreLeFr"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "solana-wallet/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

#[test]
#startup_wait = 100000

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./tests/programs/metaplex_token_metadata.so"